name: Python CI

on:
    push:
        branches:
            - main
    
    pull_request:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2

            - name: Set up Python
              uses: actions/setup-python@v2
              with:
                python-version: '3.9'

            - name: Instalación dependencias
              run: pip install -r requirements.txt
              working-directory: .

            - name: Build and start services
              run: |
                docker compose up --build -d
              working-directory: .

            - name: Run test
              run: docker compose exec web pytest
              working-directory: .

            - name: Stop and clean Docker Compose
              run: |
                docker compose down
              working-directory: .
